cmtemplate/urls.py
from django.urls import path
from . import views

app_name = 'cmtemplate'

urlpatterns = [
    path('cm/templates/', views.templates, name='templates'),
    path('cm/templates/template/get/<str:name>', views.get, name='get'),
    path('cm/templates/template/create/', views.create, name='create'),
    path('cm/templates/template/update/<str:name>', views.update, name='update'),
    path('cm/templates/template/delete/<str:name>', views.delete, name='delete'),
    path('cm/templates/getall/', views.getall, name='getall'),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('inventory/', views.inventory, name='inventory'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmtemplate.urls')),
    path('', include('inventory.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cmcollect/models.py
from django.db import models

# Create your models here.

cmdeploy/models.py
from django.db import models

# Create your models here.

cmtemplate/models.py
from django.db import models

# Create your models here.
class Template(models.Model):
    template_name = models.CharField(max_length=64,blank=False, null=False, primary_key=True, unique=True)
    description = models.CharField(max_length=128, blank=True)
    template_content = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.template_name

inventory/models.py
from email.policy import default
from django.db import models
# from django_cryptography.fields import encrypt


class Variable(models.Model):
    var_name = models.CharField(max_length=64,null=False, primary_key=True, unique=True)
    var_content = models.JSONField(blank=True, default=dict)

    def __str__(self):
        return self.var_name

class Group(models.Model):
    group_name = models.CharField(max_length=64,null=False, primary_key=True, unique=True)
    vars = models.ForeignKey(Variable, on_delete=models.SET_DEFAULT, default=dict)

    def __str__(self):
        return self.group_name

class Host(models.Model):
    name = models.CharField( max_length=64, null=False, primary_key=True, unique=True)
    ipaddr = models.GenericIPAddressField(unique=True, null=False, blank=False)
    groups = models.ManyToManyField(Group, blank=True, default="all")

    def __str__(self):
        return self.name

cmtemplate/forms.py
from django import forms

class TemplateCreateForm(forms.Form):
    name = forms.CharField(label="Template Name", max_length=64)
    description = forms.CharField(label="Template Description", max_length=128, required=False)
    content = forms.CharField(widget=forms.Textarea, required=False, label="Template Content")

class TemplateUpdateForm(forms.Form):
    description = forms.CharField(widget=forms.TextInput(attrs={"class":"fake-template-update-descr"}), label="Description", max_length=128, required=False)
    content = forms.CharField(widget=forms.Textarea(attrs={"class":"fake-template-update-content"}), required=False)

cmcollect/views.py
from django.shortcuts import render

# Create your views here.

cmdeploy/views.py
from django.shortcuts import render

# Create your views here.

cmtemplate/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse,HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Template
from .forms import TemplateCreateForm, TemplateUpdateForm

## TEMPLATE CRUD OPERATIONS
def get(request,name):
    qs = Template.objects.filter(template_name=name).values(
            "template_name", "description", "template_content")
    
    return JsonResponse(qs[0])

def create(request):
    form = TemplateCreateForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        temp = Template(
            template_name=cd["name"],
            description=cd["description"],
            template_content=cd["content"])
        temp.save()
    return redirect('cmtemplate:templates')

def update(request,name):
    form = TemplateUpdateForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        print(cd)
        temp = Template.objects.get(template_name=name)
        temp.description = cd["description"]
        temp.template_content = cd["content"]
        temp.save()
        return redirect('cmtemplate:templates')

@csrf_exempt
def delete(request, name):
    temp = Template.objects.get(template_name=name)
    temp.delete()
    return HttpResponse(status=200)

def getall(request):
    qs = Template.objects.values('template_name', 'description', 'created', 'updated')
    return JsonResponse({"data":list(qs)})

## TEMPLATE VIEW
def templates(request):
    
    createform = TemplateCreateForm()
    updateform = TemplateUpdateForm()
    context = {
        "active_page":"change-management / templates",
        "template_create_form":createform,
        "template_update_form":updateform,
        }

    return render(
        request, 
        'pages/change_management/templates.html',
        context=context)

inventory/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse,HttpResponse
from .models import Group, Host, Variable


## INVENTORY VIEW
def inventory(request):
    
    # createform = TemplateCreateForm()
    # updateform = TemplateUpdateForm()
    # context = {
    #     "active_page":"change-management / templates",
    #     "template_create_form":createform,
    #     "template_update_form":updateform,
    #     }
    context =  {"active_page":"inventory"}
    hostqs = Host.objects.filter(groups__in=["all"])

    print("x"*50)
    print(hostqs)
    print("x"*50)
    return render(
        request, 
        'pages/inventory/inventory.html',
        context=context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WebNet | {% block title%} {% endblock title %}</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'fontawesome/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/docs.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block head %}
  {% endblock head %}

</head>

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Main Navbar -->
    {% include 'partials/_navbar.html' %}
    <!-- Main Sidebar -->
    {% include 'partials/_sidebar.html' %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">{% block header_title %}{% endblock header_title %}</h1>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">{{active_page}}</li>
              </ol>
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          {% block content %} {% endblock content %}
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Main Footer -->
    {% include 'partials/_footer.html' %}
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'js/adminlte.min.js' %}"></script>
  <!-- Custom Codes -->
  <script src="{% static 'js/main.js' %}"></script>
  {% block script %} {% endblock script %}
</body>

</html>

templates/forms/template_add_form.html
<form method="post" action="template/create/">
    {% csrf_token %}
    <div class="form-group">
        <label>Template Name</label>
        <input type="text" name="template_name" class="form-control" placeholder="Template Name">
    </div>
    <div class="form-group">
        <label>Description</label>
        <input type="text" name="description" class="form-control" placeholder="Template Description">
    </div>
    <div class="form-group">
        <label>Content</label>
        <textarea id="template-add-content" name="template_content" class="p-3"></textarea>
    </div>
    <div class="d-flex justify-content-between">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

templates/modals/_template_add_modal.html
{% load crispy_forms_tags %}
<div class="modal fade" id="modal-add-template">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title">New Template</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        {{ template_create_form|crispy }}
        <div class="d-flex justify-content-between">
          <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-success">Save</button>
      </div>
      </div>
    </div>
  </div>
</div>

templates/modals/_template_modal.html
<div class="modal fade" id="modal-template">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title text-info fake-modal-update-title"></h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <div class="modal-body fake-modal-update-body"></div>
    </div>
  </div>
</div>

templates/modals/_template_modals.html
{% load crispy_forms_tags %}
<!--Template Add Modal-->
<div class="modal fade" id="modal-template-add">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">New Template</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="template/create/">
          {% csrf_token %}
          {{ template_create_form|crispy }}
          <div class="d-flex justify-content-between">
            <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-success">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!--Template Update Modal-->
<div class="modal fade" id="modal-template-update">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title fake-template-update-title"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="template-update-form" method="post" action="" class="fake-template-update-form">
          {% csrf_token %}
          {{ template_update_form|crispy }}
          <div class="d-flex justify-content-between">
            <button id="template-update-data-dismiss" type="button" class="btn btn-warning"
              data-dismiss="modal">Cancel</button>
            <button id="template-update-submit" type="submit" class="btn btn-success">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!--Template Detail Modal-->
<div class="modal fade" id="modal-template-detail">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title fake-template-detail-title"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label>Template Description</label>
          <input readonly type="text" class="form-control fake-template-detail-descr">
        </div>
        <div class="form-group">
          <label>Template Content</label>
          <textarea readonly class="form-control fake-template-detail-content" cols="40" rows="10"></textarea>
        </div>
      </div>
    </div>
  </div>
</div>

templates/pages/change_management/collect.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}Collect{% endblock title %}

{% block head %}
<!--Datatables CSS-->
<link rel="stylesheet" href="{% static 'datatables/dataTables.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'datatables/responsive.bootstrap4.min.css'%}">
{% endblock head %} 

{% block header_title %}Collect Configuration{% endblock header_title %}

{% block content %}
<div class="row">
	<div class="col-12">
		<button type="button" class="btn btn-primary btn-sm mb-2" data-toggle="modal" data-target="#modal-add-template">New Task</button>
	</div>
</div>
<div class="row">
	<div class="col-12">
		<!--Card Header-->
		<div class="card table table-responsive">
			<div class="card-header bg-info">
				<h3 class="card-title">Task Table</h3>
			</div>
		<!--Card Body-->
		<div class="card-body">
			<table id="tasks-table" class="table table-borderless table-hover">
			<thead>
				<tr>
					<th>Task Name</th>
					<th>Description</th>
					<th>Created</th>
					<th>Status</th>
					<th>Result</th>
				</tr>
			</thead>
				<tbody>
					{% for cell in data %}
					<tr>
						<td>{{cell.task_name}}</td>
						<td>{{cell.description}}</td>
						<td>{{cell.created}}</td>
						<td>{{cell.status}}</td>
            <td>{{cell.result}}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		</div>
	</div>
</div>
{% endblock content%}

{% block script %}
<!--DataTables JS-->
<script src="{% static 'datatables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'datatables/dataTables.bootstrap4.min.js'%}"></script>
<script src="{% static 'datatables/dataTables.responsive.min.js'%}"></script>
<script src="{% static 'datatables/responsive.bootstrap4.min.js'%}"></script>
<script>
	$(document).ready(function() {
    $('#tasks-table').DataTable( {
        "ajax": 'tasks/get',
        "columns": [
            { "data": "task_name" },
            { "data": "description" },
            { "data": "created" },
            { "data": "status" },
            { "data": "result" },
        ]
    } );
} );
</script>
{% endblock script%}

templates/pages/change_management/templates.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Templates{% endblock title %}

{% block head %}
<!--Datatables CSS-->
<link rel="stylesheet" href="{% static 'datatables/dataTables.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'datatables/responsive.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'datatables/select.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'datatables/buttons.bootstrap4.min.css'%}">
<!--CodeMirror CSS
	<link rel="stylesheet" href="{% static 'codemirror/codemirror.css'%}">
	<link rel="stylesheet" href="{% static 'codemirror/theme/monokai.css'%}">
	<link rel="stylesheet" href="{% static 'codemirror/addon/scroll/simplescrollbars.css'%}">
	-->

{% endblock head %}

{% block header_title %}Templates{% endblock header_title %}

{% block content %}
<div class="row">
	<div class="col-12">
		<!--Card Header-->
		<div class="card table table-responsive">
			<div class="card-header bg-gray">
				<h3 class="card-title">Template Table</h3>
			</div>
			<!--Card Body-->
			<div class="card-body">
				<table id="template-table" class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>Template Name</th>
							<th>Description</th>
							<th>Created</th>
							<th>Modified</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Template Name</th>
							<th>Description</th>
							<th>Created</th>
							<th>Modified</th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
</div>
{% include 'modals/_template_modals.html' %}
{% endblock content%}

{% block script %}
<!--DataTables JS-->
<script src="{% static 'datatables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'datatables/dataTables.bootstrap4.min.js'%}"></script>
<script src="{% static 'datatables/dataTables.responsive.min.js'%}"></script>
<script src="{% static 'datatables/responsive.bootstrap4.min.js'%}"></script>
<script src="{% static 'datatables/select.bootstrap4.min.js'%}"></script>
<script src="{% static 'datatables/dataTables.select.min.js'%}"></script>
<script src="{% static 'datatables/dataTables.buttons.min.js'%}"></script>
<script src="{% static 'datatables/buttons.bootstrap4.min.js'%}"></script>
<!--CodeMirror JS
<script src="{% static 'codemirror/codemirror.js'%}"></script>
<script src="{% static 'codemirror/mode/jinja2/jinja2.js'%}"></script>
<script src="{% static 'codemirror/display/autorefresh.js'%}"></script>
<script src="{% static 'codemirror/addon/lint/lint.js'%}"></script>
<script src="{% static 'codemirror/addon/scroll/simplescrollbars.js'%}"></script>
-->
<!--Template Page JS-->
<script src="{% static 'js/template.js'%}"></script>
{% endblock script%}

templates/pages/inventory/inventory.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Inventory{% endblock title %}

{% block head %}
<!--Datatables CSS-->
<link rel="stylesheet" href="{% static 'datatables/dataTables.bootstrap4.min.css'%}">
<link rel="stylesheet" href="{% static 'datatables/responsive.bootstrap4.min.css'%}">
{% endblock head %}

{% block header_title %}Inventory{% endblock header_title %}

{% block content %}
{% endblock content %}

templates/partials/_footer.html
  <!-- Main Footer -->
  <footer class="main-footer text-center">
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022 byavuz.</strong> All rights reserved.
  </footer>

templates/partials/_navbar.html
<!-- Navbar -->
<nav id="topnav" class="main-header navbar navbar-expand border-bottom-0 bg-lightblue navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
  </ul>
  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <div class="theme-switch-wrapper nav-link">
        <label class="theme-switch" for="checkbox">
          <input type="checkbox" id="checkbox" />
          <span class="slider round"></span>
        </label>
      </div>
    </li>
      
  </ul>
</nav>
<!-- /.navbar -->

templates/partials/_sidebar.html
{% load static %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img src="{% static 'images/logo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
      style="opacity: .8">
    <h3 class="brand-text font-weight-light">WEBNET</h3>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu"
        data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-desktop"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'inventory:inventory' %}"
            class="nav-link {% if 'inventory' in active_page %} active {% endif %}">
            <i class="nav-icon fas fa-server"></i>
            <p>
              Inventory
            </p>
          </a>
        </li>
        <li class="nav-item  {% if 'change-management' in active_page %} menu-open {% endif %} ">
          <a href="#" class="nav-link {% if 'change-management' in active_page %} active {% endif %}">
            <i class="nav-icon fab fa-hive"></i>
            <p>
              Change Management
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'cmtemplate:templates' %}"
                class="nav-link {% if 'templates' in active_page %} active {% endif %}">
                <p>Templates</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link {% if 'collect' in active_page %} active {% endif %}">
                <p>Collect</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link {% if 'provision' in active_page %} active {% endif %}">
                <p>Deploy</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>